In [ ]:
#1.auto-mpg.csv 파일을 읽어 와서
#2.컬럼명을 지정하고
# 3. horespower의 '?' 값을 이전 값으로 대체
# 4.horespower 를 카테고리 변수로 : 구간은 4개로
#     low,midium,m_midium,height로
# 5.horespower 를 더미 컬럼으로 추가
# 6.origin 컬럼을 더미 컬럼으로 ->1:USA 2:KR 3:EU로 변경

In [2]:
# %load fonts.py
#!/usr/bin/env python

# In[ ]:


# matplotlib 한글 폰트 문제 해결
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc
import platform 

if platform.system() == 'Darwin':   # Mac 환경 폰트 지정
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    rc('font', family='Malgun Gothic')
    
plt.rc('axes', unicode_minus=False)

In [3]:
#1.auto-mpg.csv 파일을 읽어 와서
#2.컬럼명을 지정하고
df=pd.read_csv('./dataset/auto-mpg.csv')
df.columns =  ['mpg','cylinders','displacement','horsepower','weight',
             'acceleration','model year','origin','name']
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
1,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
2,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
3,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
4,15.0,8,429.0,198.0,4341.0,10.0,70,1,ford galaxie 500
...,...,...,...,...,...,...,...,...,...
392,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
393,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
394,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
395,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
396,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [ ]:
# 3. horespower의 '?' 값을 이전 값으로 대체
df=df['horespower'].fillna(method='ffill',inplace=True)

In [ ]:
# 4.horespower 를 카테고리 변수로 : 구간은 4개로
#     low,midium,m_midium,height로
# 5.horespower 를 더미 컬럼으로 추가
# 6.origin 컬럼을 더미 컬럼으로 ->1:USA 2:KR 3:EU로 변경